/* ************** 外部链接的url ***************/
export const DATE_DETAIL = 'http://mytime.longhu.net:39649/schedule/PAGE_SCHEDULE_PC/main.html?option=openDesc&123456789&scheduleId='// 日程详情
export const DATE_MORE = 'http://mytime.longhu.net:39649/schedule/PAGE_SCHEDULE_PC/main.html'// 日程主页
export const RESUME = 'http://ps.longhu.net/psp/ps/EMPLOYEE/HRMS/h/?tab=HPS_EMP_INFO'// 个人简历
export const PAY = 'http://ps.longhu.net/psp/ps/EMPLOYEE/HRMS/h/?tab=HPS_EMPL_SEV'// 薪酬福利
export const NEWLIST = 'http://www.oa.longhu.net/apps/pages/news/default.aspx'// 新闻列表
// export const NEWLIST = 'http://demo.oa.longhu.net/apps/pages/news/default.aspx'// 新闻列表(测试)
export const NEWSDETAIL = 'http://www.oa.longhu.net/news/archive/'// 新闻详情
// export const NEWSDETAIL = 'http://demo.oa.longhu.net/news/archive/'// 新闻详情(测试)
export const WORKCIRCLE = 'http://www.oa.longhu.net/apps/pages/forum/dichan/'// 工作圈
export const LFCLOUD = 'http://uc.longhu.net/apps/pages/ToTokenPage.aspx'// 龙湖云
export const MAILS = 'http://uc.longhu.net/apps/pages/portal/signon263.aspx'// 邮箱
export const KNOWLEDGE = 'http://www.oa.longhu.net/apps/pages/knowledge/'// 我要学习--知识中心
export const DATE_ADD = 'http://mytime.longhu.net:39649/schedule/PAGE_SCHEDULE_PC/main.html?option=add&123456789'// 添加日程
export const FULLVIEW = 'http://oraapp1.longhu.net:7103/'// 全景计划首页
export const FULLVIEW_DETAIL = 'http://oraapp1.longhu.net:7103/wpmplan/faces/g_task.jsf?zutuan_code='// 全景计划详情
export const LEAVE = 'http://uc.longhu.net/apps/pages/workattendance/workattendance-form.aspx?type=leave'// 我要申请--请假申请
export const REIMBURSEMENT = 'http://newcost.longhu.net/cost/Main/Main.aspx?mnuno=FB_Reimbursement'// 我要申请--日常报销申请
export const DCGONGWEN = 'http://www.oa.longhu.net/apps/pages/docs/dcgongwen/docs-create-form.aspx'// 新建公文
export const TRAVELLING = 'http://uc.longhu.net/apps/pages/workattendance/workattendance-form.aspx?type=travelling'// 我要出差--出差申请
export const CARFAREAPPLY = 'http://oahr.longhu.net/apps/pages/oahr/carfare-apply-form.aspx'// 我要申请--车补申请
export const BENEFITCLASH = 'http://uc.longhu.net/apps/pages/longfor/benefitclash/benefitclash-confirm.aspx?categoryid=39f08e8e-c4c2-4f70-bb4d-3b4e14be71c2'// 利益冲突申请
export const SERVICEDESK = 'http://itil.longhu.net:88/servicedesk.htm'// IT运维报事
export const FEEDBACK = 'http://itplus.longhu.net/web/oainput/feedback/R?token=37affdd6-b01f-49f8-b1dd-82f47bc21ad5'// IT+我要反馈
export const DCBAOBIAO = 'http://www.oa.longhu.net/apps/pages/docs/dcbaobiao/docs-create-form.aspx'// 新建报表
export const RECOMMENDATION = 'http://www.hotjob.cn/wt/Longfor/web/index/innerLogin!loginUser?brandCode=1&casFlag=Y&ticket=540290e7372d91e5d1b378c275eae55149a2ad22ecb12a3a042dafbbc59a67ea2305b808438c4c6e7f9a50e4f178448d2bb2f30e9fa742dab1d888f49e1a43a219f23d5ecc1521518c7681f52a10204aafc8ed6fc1362df316920218003364dbebeb1b4022bb18c4f2bdc8c5e9b8bfeead197f7ca3d9eecdf000838e236d00dff04d7dae7bec5d6f24f7f03a7fd2b585'// 内部推荐
export const PSVALIDATE = 'http://pcs.longhu.net/web/processCenter/rzdl/certificationApplication/psValidate?custom_token=359df758-0161-48e9-97c0-f7e982a93de6'// 证明开具
export const SYRVEYFORM = 'http://www.oa.longhu.net/apps/pages/survey/survey-form.aspx'// 新建调查
export const RECRUITAPPLY = 'http://oahr.longhu.net/apps/pages/oahr/RM-RecruitApply-form.aspx'// 招聘需求申请
export const NEWSFORM = 'http://www.oa.longhu.net/apps/pages/news/news-form.aspx'// 提交新闻
export const EXACCOUNTAPPLY = 'http://uc.longhu.net/apps/pages/longfor/authority/audit-external-account-apply-form.aspx'// 外部帐号申请
export const NCACCOUNTAPPLY = 'http://uc.longhu.net/apps/pages/longfor/authority/audit-nc-account-apply-form.aspx'// NC帐号申请
export const MOAACCOUNTAPPLY = 'http://uc.longhu.net/apps/pages/longfor/authority/audit-moa-account-apply-form.aspx'// MOA帐号申请
export const BATCHACCOUNTBOARD = 'http://uc.longhu.net/apps/pages/longfor/authority/audit-batch-account-on-boarding-form.aspx'// 物业/商业批量创建帐号
export const CONTACT = 'http://www.longfor.com/contact/36/'// 廉洁举报
export const WORKRELATION = 'http://www.oa.longhu.net/apps/pages/workrelation-multi/dcgs/WorkRelation-multilib-form.aspx'// 我要申请--工作联系单
export const ROLENAV = 'http://guc.longhu.net/Role/Nav'// 我要申请--权限申请
export const GOHOME = 'http://uc.longhu.net/apps/pages/workattendance/workattendance-form.aspx?type=leave&leaveCategory=gohome'// 我要申请--探亲申请
export const ZMKJ = 'http://uc.longhu.net/apps/pages/ToTokenPage.aspx?TypeName=zm_kj'// 我要申请--证明申请
export const MEETINGFORM = 'http://www.oa.longhu.net/apps/pages/meeting/meeting-form.aspx'// 我要开会--会议申请
export const SCHEDULE = 'http://mytime.longhu.net:39649/schedule/PAGE_SCHEDULE_PC/main.html?123456789'// 我要开会--日程管理
export const MRRTINGROOM = 'http://www.oa.longhu.net/apps/pages/meeting/meeting-room-report.aspx'// 我要开会--会议室状态
export const HOTEL = 'http://mytime.longhu.net:39649/moapproval/PAGE_HR/uploadexcel.html'// 我要出差--协议酒店/专票信息
export const LMEZ = 'http://uc.longhu.net/apps/pages/ToTokenPage.aspx?TypeName=lmez'// 我要学习--新龙门e栈
export const XISBN = 'http://www.oa.longhu.net/wenku/book/X_ISBN_33.aspx'// 我要学习--龙湖方法论
export const MANUAL = 'http://www.oa.longhu.net/wenku/book/longfor_quality_manual.aspx'// 我要学习--工程质量红宝书
export const MARKETING = 'http://www.oa.longhu.net/wenku/book/longfor_marketing_manual.aspx'// 我要学习--营销操盘实物手册
